'use client'
import "./globals.css";
import StoreContextProvider from "./context/StoreContext";
import Footer from "./copmonents/footer/page";
import Navbar from "./copmonents/navbar/page";
import { useState } from "react";
import Login from '@/app/login/page'
import { usePathname } from 'next/navigation'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode,
// }>)  {
//   // const [showLogin, setShowLogin] = useState(false)
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} scroll-smooth sm:px-20 px-6 antialiased`}
//       >
//         <StoreContextProvider>
//           {/* {showLogin ? <Login/> : <></>} */}
//         {/* <Navbar setShowLogin={setShowLogin} /> */}
//         {children}
//         <Footer />
//         </StoreContextProvider>
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [showLogin, setShowLogin] = useState(false);
  const pathname = usePathname()
  const isAdmin = pathname.startsWith('/admin')

  return (
    <html lang="en">
      <body className="scroll-smooth sm:px-20 px-6 antialiased">
        <StoreContextProvider>
          {showLogin && <Login setShowLogin={setShowLogin} />}
          {!isAdmin && <Navbar setShowLogin={setShowLogin} />}
          {children}
          {!isAdmin && <Footer />}
        </StoreContextProvider>
      </body>
    </html>
  );
}

